// <auto-generated />
using CTVoicer.Negocio.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CTVoicer.Negocio.Migrations
{
    [DbContext(typeof(CTVoicerContext))]
    [Migration("20190812123725_CTVoicer")]
    partial class CTVoicer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CTVoicer.Entidades.Frota", b =>
                {
                    b.Property<int>("IdFrota")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdFrota");

                    b.ToTable("Frotas");
                });

            modelBuilder.Entity("CTVoicer.Entidades.Veiculo", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdFrota");

                    b.Property<int>("NumPassageiros");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdVeiculo");

                    b.HasIndex("IdFrota");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("CTVoicer.Entidades.Veiculo", b =>
                {
                    b.HasOne("CTVoicer.Entidades.Frota", "Frota")
                        .WithMany("Veiculos")
                        .HasForeignKey("IdFrota")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
